name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9.8.0
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm' # Найстабільніший варіант кешування

      - run: pnpm install --frozen-lockfile
      
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - run: pnpm exec nx affected -t lint test build e2e --base=origin/main